Format TWP18 and add test
PyAr/PyZombis pull request #108
Opened 2021-06-22 17:21 UTC by LeoCumpli21

## Summary

This PR closes LeoCumpli21/PyZombis#32 by formatting all code with `black`. Also, I added a web test for activecode 5.
*Note*: I didn't focus on redaction nor grammar.

## Checklist

- [ ] Variables, functions and comments are translated to Spanish
- [ ] Functions follow underscore notation
- [ ] Spell check done & typos fixed
- [ ] All python code is PEP8 compliant
- [ ] Test coverage with Playwright implemented; locators are Pyhton code
- [ ] Reviewers assigned (all peers & at least 1 mentor)

## Screenshots

https://user-images.githubusercontent.com/80920858/122971114-4a2b5700-d354-11eb-8cf6-8f34cc8c1a64.mp4

2021-06-29 13:57 UTC, angelasofiaremolinagutierrez commented on _sources/lectures/TWP18.rst
> +    x = "aguacate"
```suggestion
    x = 'aguacate'
```
The exercise says:
> ¿Puedo usar comillas simples, dobles o triples?

I think there are three `print()` functions, each one to show each kind of possibility to make a string: `'` `"` `"""`.

2021-06-29 14:55 UTC, LeoCumpli21 commented on _sources/lectures/TWP18.rst
> +    x = "aguacate"
Right! Thanks.

2021-07-02 03:15 UTC, y-martinez approved these changes
I left some suggestions but In general LGTM,

2021-07-02 03:15 UTC, y-martinez commented on _sources/lectures/TWP18.rst
> +    como argumento el caracter con el cual separar un string. Guardar el día, mes y el año
```suggestion
    como argumento el caracter con el cual separar un string. Guardar el día, mes y el año en formato de cadena 
```

2021-07-02 03:15 UTC, y-martinez commented on _sources/lectures/TWP18.rst
>  + Ejemplo de un programa que lee una palabra y reemplaza las vocales con "*"
```suggestion
+ Ejemplo de un programa que lee una palabra y reemplaza las vocales por ``"*"``
```

2021-07-02 03:39 UTC, NicolasSandoval requested changes
Nice work, but in the 'Concentración' exercises capital letters are not considered, maybe you can add the `lower()` function to the words or add in the text that only works with lowercase.

2021-07-02 16:33 UTC, LeoCumpli21 commented
> Nice work, but in the 'Concentración' exercises capital letters are not considered, maybe you can add the `lower()` function to the words or add in the text that only works with lowercase.

Done @NicolasSandoval 😄

2021-07-02 21:43 UTC, NicolasSandoval approved these changes
Great! Thanks.

2021-07-02 21:43 UTC, merged