TWP30 fixed
PyAr/PyZombis pull request #117
Opened 2021-06-28 19:24 UTC by LeoCumpli21

## Summary

This PR closes LeoCumpli21/PyZombis#37. I only focused on python code, not on grammar.

## Checklist

- [ ] Variables, functions and comments are translated to Spanish
- [ ] Functions follow underscore notation
- [ ] Spell check done & typos fixed
- [ ] All python code is PEP8 compliant
- [ ] Test coverage with Playwright implemented; locators are Pyhton code
- [ ] Reviewers assigned (all peers & at least 1 mentor)

2021-06-29 20:23 UTC, angelasofiaremolinagutierrez requested changes

2021-06-29 20:23 UTC, angelasofiaremolinagutierrez commented on _sources/lectures/TWP30.rst
> +                print("Bajo")
It might be best to do this exercise with the new Brython module. The `input()` function is displayed as an alert on the page, so you input random numbers but you can't see if the number is higher or lower because the prints (`print("Alto"`) and `print("Bajo")`) aren't showed until you guess.

2021-06-29 20:23 UTC, angelasofiaremolinagutierrez commented on _sources/lectures/TWP30.rst
> +                print("Alto")
Same thing for this one.

2021-06-30 16:29 UTC, LeoCumpli21 commented on _sources/lectures/TWP30.rst
> +                print("Bajo")
I'll take a look at it.

2021-06-30 23:47 UTC, LeoCumpli21 commented
I'm closing this PR and reopening it when Brython's console is displayed on Runestone.

2021-07-02 16:04 UTC, y-martinez commented
> I'm closing this PR and reopening it when Brython's console is displayed on Runestone.

Maybe a better choice is to open it again and change the status to Draft and put [WIP] in the title like the #118 that I need the Brython module.

2021-07-03 02:52 UTC, angelasofiaremolinagutierrez commented
@LeoCumpli21 I'm reopening this PR now that this https://github.com/angelasofiaremolinagutierrez/RunestoneComponents/pull/13 is merged with master.

2021-07-04 13:33 UTC, y-martinez approved these changes

2021-07-04 21:22 UTC, NicolasSandoval approved these changes
Looks good!, there are some visual details. I think @angelasofiaremolinagutierrez  will work on this later.

2021-07-04 21:22 UTC, merged