Fix TWP38
PyAr/PyZombis pull request #120
Opened 2021-07-01 00:38 UTC by LeoCumpli21

## Summary

This PR closes LeoCumpli21/PyZombis#39 by:
* Accomplishing with the checklist.
* Adding brython module in the final exercise for the `eval` function to work.

## Checklist

- [ ] Variables, functions and comments are translated to Spanish
- [ ] Functions follow underscore notation
- [ ] Spell check done & typos fixed
- [ ] All python code is PEP8 compliant
- [ ] Test coverage with Playwright implemented; locators are Pyhton code
- [ ] Reviewers assigned (all peers & at least 1 mentor)

2021-07-04 13:45 UTC, y-martinez commented on _sources/lectures/TWP38.rst
>  + El signo ">>>" indica que Python está "listo" para recibir
Maybe this should remove it until we can add the Python interpreter here if is possible.

2021-07-04 13:51 UTC, y-martinez requested changes

2021-07-04 13:51 UTC, y-martinez commented on _sources/lectures/TWP38.rst
>  Recuerdo
Recuerda o Recuerde

2021-07-04 13:51 UTC, y-martinez commented on _sources/lectures/TWP38.rst
> +  para lenguaje máquina
```suggestion
  a lenguaje máquina
```

2021-07-04 13:51 UTC, y-martinez commented on _sources/lectures/TWP38.rst
> +    print("Este programa ilustra el comportamiento caótico.")
This example doesn't show anything but in the browser's console appears the output.

2021-07-04 16:50 UTC, LeoCumpli21 commented on _sources/lectures/TWP38.rst
> +    print("Este programa ilustra el comportamiento caótico.")
It actually does display in the browser's console. Locally, It displays it just fine. 

![caos](https://user-images.githubusercontent.com/80920858/124392946-b6e01300-dcbd-11eb-8983-4cdae0fbd5e4.PNG)

2021-07-05 15:35 UTC, LeoCumpli21 commented on _sources/lectures/TWP38.rst
>    comandos
```suggestion
```

2021-07-05 15:36 UTC, LeoCumpli21 commented on _sources/lectures/TWP38.rst
>  Recuerdo
```suggestion
Recuerde
```

2021-07-05 21:35 UTC, y-martinez approved these changes
LGTM 👍🏼

2021-07-05 23:15 UTC, NicolasSandoval approved these changes
LGTM!

2021-07-05 23:15 UTC, merged