14 quiz2
PyAr/PyZombis pull request #124
Opened 2021-07-03 22:12 UTC by y-martinez

## Summary

This PR close the y-martinez/PyZombis#14

## Checklist

- [x] Variables, functions and comments are translated to Spanish
- [x] Functions follow underscore notation
- [x] Spell check done & typos fixed
- [x] All python code is PEP8 compliant
- [x] Test coverage with Playwright implemented; locators are Pyhton code
- [x] Reviewers assigned (all peers & at least 1 mentor)

2021-07-06 17:12 UTC, angelasofiaremolinagutierrez requested changes

2021-07-06 17:12 UTC, angelasofiaremolinagutierrez commented on _sources/quiz/Quiz2.rst
> +    **Nota**: recuerde que no es un triángulo cuando el lado de mayor longitud es mayor o igual que la suma de los otros dos. |br| |br|
The instruction is very clear now, but some of the test are still failing. The third example is ``es_triangulo(4, 2, 6)`` -> ``"Escaleno"`` ` But the answer is not actually "Escaleno". The largest side is 6 and the sum of the other two sides is 4+2=6. 
6 >= 6 That means that the answer would be "No es triángulo"
That is also the reason why test 3 is failing:
![image](https://user-images.githubusercontent.com/10239480/124640526-276c6880-de53-11eb-839b-3a80ba6eaffe.png)
Test 3 says: 
self.assertEqual(es_triangulo(2, 1, 3), "Escaleno", "Esperado: Escaleno")
but the answer should be "No es triángulo" since 3 >= (2+1)

2021-07-06 22:45 UTC, y-martinez commented on _sources/quiz/Quiz2.rst
> +    **Nota**: recuerde que no es un triángulo cuando el lado de mayor longitud es mayor o igual que la suma de los otros dos. |br| |br|
Oh gosh, 😅 I forgot to change the tests cases, thanks I am going to change it 👍🏼

2021-07-07 04:13 UTC, NicolasSandoval approved these changes
Great! Thanks.

2021-07-07 04:14 UTC, merged