Add Hangman challenge
PyAr/PyZombis pull request #131
Opened 2021-07-14 19:27 UTC by LeoCumpli21

## Summary

This PR closes LeoCumpli21/PyZombis#13.

I implemented the Hangman game from the original course. I did it as a progressive exercise, where most activecodes need the previous ones to be completed before them to work appropriatly. 

About the `Playwright` test:
* It is a big test due to the fact that the activecodes are linked to each other with the `:include: ` parameter.
* In the video below, sometimes the screen seems to stall. This happens because the *dialog prompts* are being handled, but Playwright doesn't show this.

## Checklist

- [ ] Variables, functions and comments are translated to Spanish
- [ ] Functions follow underscore notation
- [ ] Spell check done & typos fixed
- [ ] All python code is PEP8 compliant
- [ ] Test coverage with Playwright implemented; locators are Pyhton code
- [ ] Reviewers assigned (all peers & at least 1 mentor)

## Screenshots

https://user-images.githubusercontent.com/80920858/125680460-5702c812-f9f8-48fe-9f21-e2e089aec3e5.mp4

2021-07-14 19:45 UTC, LeoCumpli21 commented
I use webkit as the browser for the playwright test. This is why locally this final version didn't gave me any problems. However, I didn't realize that with chrome Playwright has trouble accepting the dialog prompt.

2021-07-17 16:51 UTC, LeoCumpli21 commented
> I use webkit as the browser for the playwright test. This is why locally this final version didn't gave me any problems. However, I didn't realize that with chrome Playwright has trouble accepting the dialog prompt, hence making the test fail.

Done! Now it works on Chrome as well.

2021-07-20 17:51 UTC, angelasofiaremolinagutierrez approved these changes
LGTM! just a couple of notes ;)

2021-07-20 17:51 UTC, angelasofiaremolinagutierrez commented on _sources/index.rst
> +   lectures/Reto01.rst
I suggest to create a different folder for these challenges you are creating. Something like: `retos/Reto01.rst`

2021-07-20 17:51 UTC, angelasofiaremolinagutierrez commented on _sources/lectures/Reto01.rst
> +            # Esto es para aumentar el tiempo de ejecución de Runestone
Is it possible to hide these lines from the activecode block? Maybe in the way we hide the tests. I don't think it's necessary for the student to see them.

2021-07-20 22:56 UTC, NicolasSandoval requested changes
LGTM! I left a few comments and suggestions.

2021-07-20 22:56 UTC, NicolasSandoval commented on _sources/lectures/Reto01.rst
> +
Perhaps here we could clarify that the names of the cities are in English

2021-07-20 22:56 UTC, NicolasSandoval commented on _sources/lectures/Reto01.rst
> +            # Debe importar otra librería
We could add another valid option, like: 
```python3
import random

random.choice(ciudades)
```

2021-07-20 22:56 UTC, NicolasSandoval commented on _sources/lectures/Reto01.rst
> +
Here we must add that the code needs to request the user to input a letter.

2021-07-20 22:56 UTC, NicolasSandoval commented on _sources/lectures/Reto01.rst
> +            dependiendo de la respuesta. **Nota**: La función se va a ejecutar dos vez para verificar si pasa las pruebas unitarias.
```suggestion
            dependiendo de la respuesta. **Nota**: La función se va a ejecutar dos veces para verificar si pasa las pruebas unitarias.
```

2021-07-20 23:42 UTC, LeoCumpli21 commented on _sources/index.rst
> +   lectures/Reto01.rst
Sure! In another PR I will tackle this 😄 Thanks for the suggestion.

2021-07-21 01:11 UTC, LeoCumpli21 commented on _sources/lectures/Reto01.rst
> +            # Esto es para aumentar el tiempo de ejecución de Runestone
I tried to hide those lines, but didn't work.

2021-07-21 02:30 UTC, NicolasSandoval approved these changes
Great work! Thanks.

2021-07-21 02:43 UTC, y-martinez approved these changes
LGTM 🚀

2021-07-23 23:14 UTC, merged