[WIP] User interface
PyAr/PyZombis pull request #139
Opened 2021-07-22 17:26 UTC by y-martinez

## Summary

(short description of what does this PR, Issue #, etc.)

## Checklist

- [X] Variables, functions and comments are translated to Spanish
- [X] Functions follow underscore notation
- [X] Spell check done & typos fixed
- [ ] All python code is PEP8 compliant
- [X] Test coverage with Playwright implemented; locators are Pyhton code
- [] Reviewers assigned (all peers & at least 1 mentor)

2021-07-23 00:52 UTC, angelasofiaremolinagutierrez requested changes
This looks great! I really like it 👍  However, there is two exercises that have an error within them.

2021-07-23 00:52 UTC, angelasofiaremolinagutierrez commented on _sources/lectures/TWP50.rst
> +    document <= html.AUDIO(id="audio" src=url_audio, controls=True)
A `,` is missing this generates an error
```suggestion
    document <= html.AUDIO(id="audio", src=url_audio, controls=True)
```

2021-07-23 00:52 UTC, angelasofiaremolinagutierrez commented on _sources/lectures/TWP50.rst
> +    d.panel <= html.H3(Aprieta los botones, id="titulo_ventana", style=dict(textAlign="center"))
This also generates an error
```suggestion
    d.panel <= html.H3("Aprieta los botones", id="titulo_ventana", style=dict(textAlign="center"))
```

2021-07-23 04:31 UTC, y-martinez commented
> This looks great! I really like it  However, there is two exercises that have an error within them.

Ohh gosh I forgot, I was thinking that I already had been resolved them. Thanks for pointing them I am going to change them

2021-07-23 15:48 UTC, angelasofiaremolinagutierrez approved these changes
Amazing! 💯

2021-07-25 19:28 UTC, LeoCumpli21 commented on _sources/lectures/TWP50.rst
> +    d.panel <= html.BUTTON("¡Aprietame!", id="btn_apretar", style=dict(margin="auto", display="block"))
```suggestion
    d.panel <= html.BUTTON("¡Apriétame!", id="btn_apretar", style=dict(margin="auto", display="block"))
```

2021-07-25 19:30 UTC, LeoCumpli21 approved these changes
Looks incredible! Congrats.

2021-07-29 01:07 UTC, NicolasSandoval approved these changes
Great job! Thanks.

2021-07-29 01:08 UTC, merged