Refactor TWP42: Bases de Datos using SQL.js
PyAr/PyZombis pull request #200
Opened 2022-03-08 20:13 UTC by shivamshan

Signed-off-by: Shivam Shandilya <shivam.stpaulsdarjeeling@gmail.com>

## Summary

This PR is based upon and fixes issues in PR #184, which ultimately may close the issue #193.<br>
The issues in PR #184 (where the SQL.js database was not accessible through activecode block) were fixed by using the `document `module provided by activecode and some javascript manipulation.<br><br>

The following are the results of this PR:

- any query (SELECT, INSERT, DELETE, etc.) can be enclosed in a string and can be executed
- a function was created to show data in tabular format
- the same format can be followed in other SQL lectures to showcase use of different queries

## Checklist

- [x] Variables, functions and comments are translated to Spanish
- [x] Functions follow underscore notation
- [x] Spell check done & typos fixed
- [x] All python code is PEP8 compliant
- [x] Test coverage with Playwright implemented; locators are Python code
- [x] Reviewers assigned (all peers & at least 1 mentor)

## Screenshots

### SELECT query execution on existing table
![Wed Mar 09 2022 01_34_03](https://user-images.githubusercontent.com/55462040/157316710-5deb653c-7927-4c55-81f7-512e99f345eb.gif)

### Creating new table and inserting data into it
![Wed Mar 09 2022 01_35_57](https://user-images.githubusercontent.com/55462040/157316720-78bf0c3e-13e9-4aa3-b347-9eeaeb3445bf.gif)

2022-03-10 04:07 UTC, shivamshan commented
Hi @reingart @angelasofiaremolinagutierrez , should I also add unittests and coverage with playwright in this PR??

2022-03-10 04:14 UTC, reingart commented
Great work @shivamshan !
There are some items that need to be revised, but in general it is useful as a Proof-of-Concept of the idea 
To move further, could you add an playwright end-2-end test? (see the /tests folder)
That will help you to get more familiar with the testing and CI tools

2022-03-10 04:30 UTC, shivamshan commented
@reingart sure I will move forward with this. Also could you tell me what revisions need to be made?

2022-03-10 19:58 UTC, reingart requested changes
Please see the comments and add a e2e test with playwright

2022-03-10 20:25 UTC, shivamshan commented on _sources/lectures/TWP42/TWP42_1.rst
> +    def formato_datos(data, width):
okay..but how would that wrapper be incorporated here in activecode? could you lead me to any example or resource

2022-03-10 20:28 UTC, shivamshan commented on _sources/lectures/TWP42/TWP42_1.rst
> +               res = db.exec(document.getElementById("create-db-script").getAttribute("query"));
it seems that brython code when run from the activecode block doesn't have DOM access, therefore the SQL.Database objects are not directly accessible...I will however look into the latter suggestion.

2022-03-11 22:57 UTC, shivamshan commented on _sources/lectures/TWP42/TWP42_1.rst
> +    def formato_datos(data, width):
I have implemented a simple wrapper for sqlite3 that currently mimics connect, execute, fetchall and close functions. Although I have not removed the formato_datos function, I have moved it along with the hidden wrapper code so students need not worry about it. But they can still use it

2022-03-11 23:00 UTC, shivamshan commented on _sources/lectures/TWP42/TWP42_1.rst
> +    time.sleep(1)
I have solved this issue by using a flag attribute that gets set only when the query gives a result. To handle bad joins, I have added a kind of timeout feature, that tells the user that the query has issues if the query takes longer that 5 seconds to give a result.

2022-03-11 23:00 UTC, shivamshan commented on _sources/lectures/TWP42/TWP42_1.rst
> +
I have added suitable comments to increase readability.

2022-03-11 23:01 UTC, shivamshan commented on _sources/lectures/TWP42/TWP42_1.rst
> +
I have added suitable comments to increase readability.

2022-03-12 03:42 UTC, reingart requested changes
The changes look good!
I made some  minor comments
I tried the code of the next exercise and it seems the execute is not working correctly: (just prints `Please check your query`)
````
cursor.execute('''create table alumnos(login varchar(8),ra integer)''')
cursor.execute('insert into alumnos values("masanori",42)')
cursor.execute('insert into alumnos values("emengarda",666)')
cursor.execute('select * from alumnos')
````
http://pyar.github.io/PyZombis/200/lectures/TWP42/TWP42_2.html

Probably you need to :
 - [ ] review execute for DDL 
 - [ ] implement commit & rollback
 - [ ] enhance a bit the error reporting (raise the excepcion thrown by sqlite)

2022-03-12 03:42 UTC, reingart commented on _sources/lectures/TWP42/TWP42_1.rst
> +       formato_datos(linhas, 30)
Here please return something similar to the original example (a for iterating over a list of dicts is ok)
No need to format the output (it is great but hides a bit the details of DB-API concepts we want to teach)

2022-03-12 03:42 UTC, reingart commented on _sources/lectures/TWP42/TWP42_1.rst
> +    # crear un cursor y ejecutar la consulta
Please add the cursor row factory, so eventually the student could copy & paste the exercise and rut in a normal python interpreter
```
    base_datos.row_factory = sqlite3.Row
```
(you can comment it provisionally until the sqlite module is more mature)

2022-03-12 14:56 UTC, shivamshan commented on _sources/lectures/TWP42/TWP42_1.rst
> +       formato_datos(linhas, 30)
updated the function to format the result from sql.js t resemble sqlite3

2022-03-12 14:57 UTC, shivamshan commented on _sources/lectures/TWP42/TWP42_1.rst
> +    # crear un cursor y ejecutar la consulta
added the above statement as comment

2022-03-12 15:04 UTC, shivamshan commented
- I updated the execute function to resemble more like the sqlite3 code. Previously it was required that all the SQL statements be inside one string and that be passed as query. But now the user can have multiple execute sttements.
- I have added functions for rollback and commit functionality, but they are currently empty because commit and rollback feature  require persistent changes to the db which is not currently supported here. I am working on a way around.

> * [X]  review execute for DDL
> * [X]  implement commit & rollback
> * [X]  enhance a bit the error reporting (raise the excepcion thrown by sqlite)

2022-03-12 15:56 UTC, reingart requested changes
Great! 
I think there is a bug that is not cleaning the last query results (repeats the same data)
The second execute should be retriving rows from the new alumnos tables
```
base_datos = connect('surfers.db')
cursor = base_datos.cursor()
query = 'SELECT * FROM surfers'
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

cursor.execute('''create table alumnos(login varchar(8),ra integer)''')
cursor.execute('insert into alumnos values("masanori",42)')
cursor.execute('insert into alumnos values("emengarda",666)')
cursor.execute('select * from alumnos')
rows = cursor.fetchall()
for row in cursor.fetchall():
    print(row)
```

2022-03-12 17:17 UTC, shivamshan commented
yes, I was not clearing the previous query, therefore the final result comprised of results of both sets of queries...with only the first result getting parsed. Now, this issue is fixed.

2022-03-12 17:39 UTC, reingart requested changes
Perfect!
A final request: you should be giving to the user a more descriptive error.
For example, if I try to query a non-existing table by mistake: 
```
query = 'SELECT * FROM wrong_table'
```
It shows a generic error `Query error. Something is wrong with the query`
I have to open the JS console to see the detailed error message:
```
Error: no such table: wrong_table
    at c.handleError (sql-wasm.js:89:254)
    at c.exec (sql-wasm.js:87:6)
    at TWP42_1.html:372:22
```
Please raise a proper Python Exception with the SQLite error text `Error: no such table: wrong_table`, so the experience is more friendly to begginers

2022-03-12 17:44 UTC, reingart requested changes

2022-03-12 17:44 UTC, reingart commented on _sources/lectures/TWP42/TWP42_1.rst
> +          pass
Please execute here a SQL "COMMIT" statement

2022-03-12 17:44 UTC, reingart commented on _sources/lectures/TWP42/TWP42_1.rst
> +          pass
Please execute here a SQL "ROLLBACK" statement

2022-03-12 23:18 UTC, shivamshan commented on _sources/lectures/TWP42/TWP42_1.rst
> +          pass
added rollback functionality

2022-03-12 23:20 UTC, shivamshan commented on _sources/lectures/TWP42/TWP42_1.rst
> +          pass
added commit functionality but cannot view its functionality as database is not persistent and new db object is created with each fetchall statement

2022-03-13 00:08 UTC, reingart approved these changes

2022-03-13 04:57 UTC, shivamshan commented
Hi @reingart , I have made some changes and added proof of concept for the rollback function. I have attached a gif showing that  both the rollback and commit statements work as they are supposed to. But they is a limitation that using the commit and rollback statements after a fetchall statement might not generate the correct output, the reason being that the db is not persistent and a new db object is created after every fetchall statment.

The following can be seen below, the commit functionality is only viable before a fetchall statement, as a new db object is created after:
![68c39395-c5cf-4b49-8d09-c9b94cd0aaf6](https://user-images.githubusercontent.com/55462040/158045673-5f0dc95c-0d7a-4141-8f13-20fd8ccc6820.gif)

The code to recreate this:
```
base_datos = connect('surfers.db')

cursor = base_datos.cursor()
cursor.execute('delete from surfers where edad<35')
base_datos.commit()
cursor.execute('SELECT * FROM surfers')

linhas = cursor.fetchall()
if(linhas!=None):
   for linha in linhas:
      print("ID    :",linha['id'])
      print("Nombre :",linha['nombre'])
      print("Pais  :",linha['pais'])
      print("Media  :",linha['media'])
      print("Estilo :",linha['estilo'])
      print("Edad  :",linha['edad'])
      print()

print("-----------------------------------------")
cursor.execute('SELECT * FROM surfers')
linhas = cursor.fetchall()
if(linhas!=None):
   for linha in linhas:
      print("ID    :",linha['id'])
      print("Nombre :",linha['nombre'])
      print("Pais  :",linha['pais'])
      print("Media  :",linha['media'])
      print("Estilo :",linha['estilo'])
      print("Edad  :",linha['edad'])
      print()
# cerrar el cursor
cursor.close()
```

2022-03-13 09:25 UTC, shivamshan commented
UPDATE:-   
The previous problem has been fixed now. The commit functionality now resembles that of sqlite3. Although the db is still not persistent, I found a way around to get get results after commit stataements.

### Result
The difference in results can be seen. The results are now in accordance with the committed transactions.

![1a3df712-0c6d-4b8b-a7e5-493ee371e761](https://user-images.githubusercontent.com/55462040/158053134-953bc086-0c07-4b6c-bdac-e87b5baab550.gif)

The code to recreate this:- 
```
base_datos = connect('surfers.db')

cursor = base_datos.cursor()
cursor.execute('delete from surfers where edad<35')
base_datos.commit()
cursor.execute('SELECT * FROM surfers')

linhas = cursor.fetchall()
if(linhas!=None):
   for linha in linhas:
      print("ID    :",linha['id'])
      print("Nombre :",linha['nombre'])
      print("Pais  :",linha['pais'])
      print("Media  :",linha['media'])
      print("Estilo :",linha['estilo'])
      print("Edad  :",linha['edad'])
      print()

print("-----------------------------------------")
cursor.execute('SELECT * FROM surfers')
linhas = cursor.fetchall()
if(linhas!=None):
   for linha in linhas:
      print("ID    :",linha['id'])
      print("Nombre :",linha['nombre'])
      print("Pais  :",linha['pais'])
      print("Media  :",linha['media'])
      print("Estilo :",linha['estilo'])
      print("Edad  :",linha['edad'])
      print()
# cerrar el cursor
cursor.close()
```

2022-03-24 05:44 UTC, reingart requested changes
I was playing a bit more with SQL.js and made a PoC a4052d6567e6e7239df2e05546ff5755c8179168 with a more clean approach (creating and accessing the JS Database object directly from brython)
I left some comments so we can finally merge this:
 - [] Resolve the conflicts and merge the PoC
 - [ ] Switch from Skulpt to Brython interpreter
 - [ ] Use JS objects directly via window.parent
 - [ ] Move the code to `_static/sqlite.py` so it can be reusable in the next activity

It would be great if we could load the surfers.db from the `_static` folder, so the INSERTs can be skipped

2022-03-24 05:44 UTC, reingart commented on _sources/lectures/TWP42/TWP42_1.rst
> +               res = db.exec(document.getElementById("create-db-script").getAttribute("query"));
You could access  `browser.window.parent` in Brython if the name is declared in the global JS namespace
See [Objects in Javascript programs](https://www.brython.info/static_doc/en/jsobjects.html)
Activecode runs in a IFRAME, so you have to access the parent window.
For a PoC implementation see [a4052d6](https://github.com/PyAr/PyZombis/commit/a4052d6567e6e7239df2e05546ff5755c8179168).
Accessing directly to JS objects will help to remove the observer and DOM manipulation to pass data

2022-03-24 05:44 UTC, reingart commented on _sources/lectures/TWP42/TWP42_1.rst
> +.. activecode:: ac_l42_1
Convert this activity from Skulp to Brython interpreter

2022-03-24 05:44 UTC, reingart commented on _sources/lectures/TWP42/TWP42_1.rst
> +    class Cursor:
Move The Cursor/Connection classes & connect function to a separate file `_static/sqlite.py`
Import it as in the Pygame ticket #201

2022-06-25 17:56 UTC, shivamshan commented
> I was playing a bit more with SQL.js and made a PoC [a4052d6](https://github.com/PyAr/PyZombis/commit/a4052d6567e6e7239df2e05546ff5755c8179168) with a more clean approach (creating and accessing the JS Database object directly from brython) I left some comments so we can finally merge this:
> 
> * [x] Resolve the conflicts and merge the PoC
> * [x]  Switch from Skulpt to Brython interpreter
> * [x]  Use JS objects directly via window.parent
> * [x]  Move the code to `_static/sqlite.py` so it can be reusable in the next activity
> 
> It would be great if we could load the surfers.db from the `_static` folder, so the INSERTs can be skipped

2022-06-29 01:48 UTC, reingart approved these changes
Great! 
Please make another PR with a test using plywright (just executing the query and checking the result)

2022-06-29 01:49 UTC, merged