Pygame POC
PyAr/PyZombis pull request #201
Opened 2022-03-15 22:15 UTC by shivamshan

## Summary

This PR is basically a **proof of concept** for adding support for pygame in activecode. Although the old brython fork for pygame is buggy, this PR still shows that it is possible to incorporate pygame in lectures.

- this PR is however not enough to teach students
- many features are not present or implemented(for ex: drawing circles or ellipses)

## Checklist

- [X] Variables, functions and comments are translated to Spanish
- [X] Functions follow underscore notation
- [X] Spell check done & typos fixed
- [X] All python code is PEP8 compliant
- [ ] Test coverage with Playwright implemented; locators are Pyhton code
- [X] Reviewers assigned (all peers & at least 1 mentor)

## Results

![50935727-13d6-486f-bc24-7d22257414ad](https://user-images.githubusercontent.com/55462040/158481274-57f2f4b1-c47c-4762-b9b3-afa9f2ac7c74.gif)

2022-03-16 01:41 UTC, reingart requested changes
Nice work!
I made some comments
It is just me or pygame takes a bit to load?

2022-03-16 01:41 UTC, reingart commented on _sources/lectures/TWP60/TWP60_1.rst
> +    import pygame
You would need to add the static folder to the PYTHONPATH (so pygame lib could be found)
You could also add it to the Brython onload function: https://www.brython.info/static_doc/en/options.html
```suggestion
    import sys
    sys.path.append("../../_static")
    ^^^^
    import pygame 
```

2022-03-16 01:41 UTC, reingart commented on .github/workflows/python-app.yml
> +        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
Instead of comment this static check, please add an option to ignore the pygame folder with `--exclude`

2022-03-16 01:41 UTC, reingart commented on requirements.txt
> +git+https://github.com/angelasofiaremolinagutierrez/RunestoneComponents.git@master#runestone
Please rebase with the main branch, your other PR#202 was merged

2022-03-16 08:01 UTC, shivamshan commented
Hi @reingart , I have made the suggested changes and you are right. It taking a while for pygame to load the results for some reason. Locally the time taken was not so much as can be seen in the GIF uploaded.

2022-03-24 05:55 UTC, reingart commented
Nice! did you check this fork https://github.com/wkta/brython-pygame/tree/master/pygame right?

2022-03-24 06:04 UTC, reingart requested changes
For an possible speed-up (module import) please try to package pygame: https://www.brython.info/static_doc/en/brython-packages.html
This should create a more compact js file

2022-07-25 04:00 UTC, chazuttu approved these changes

2022-08-24 01:06 UTC, reingart commented
This PR was superseded by #222

2022-08-24 01:06 UTC, closed without merging