Saving progess using local storage
PyAr/PyZombis pull request #281
Opened 2023-05-15 04:21 UTC by sujith-rek

## Summary

active code changes that facilitate progress saving

## Checklist

- [X] Variables, functions, and comments are translated into Spanish
- [X] Functions follow underscore notation
- [X] Spell check done & typos fixed
- [X] All Python code is PEP8 compliant
- [X] Test coverage with Playwright implemented; locators are Python code
- [ ] Reviewers assigned (all peers & at least 1 mentor)

## Screenshots

(prefer Playwright recorded video or animated gif)

2023-05-23 00:34 UTC, NicolasSandoval approved these changes
LGTM!

2023-06-01 00:02 UTC, reingart requested changes
Great work!

Please see my comments so we can merge this PR.

2023-06-01 00:02 UTC, reingart commented on tests/test_TWP42.py
> +    page.fill("text=RunResetLoad History21 1from sqlite3 import connect2con = connect('alumnos.bd')3cur = >> textarea", "cur.execute('''create table alumnos(login_id varchar(8),pass integer)''')")
Does this change in the locator break any other test?

2023-06-01 12:51 UTC, sujith-rek commented on tests/test_TWP42.py
> +    page.fill("text=RunResetLoad History21 1from sqlite3 import connect2con = connect('alumnos.bd')3cur = >> textarea", "cur.execute('''create table alumnos(login_id varchar(8),pass integer)''')")
no, all the other tests working fine

2023-06-01 12:52 UTC, sujith-rek commented on requirements.txt
> +git+https://github.com/sujith-rek/RunestoneComponents.git@master#runestone
yes, done

2023-06-05 15:06 UTC, fzuccolo approved these changes

2023-06-08 00:04 UTC, merged