English translation of titles
PyAr/PyZombis pull request #293
Opened 2023-10-24 23:24 UTC by ivanuxowo

2023-11-06 00:37 UTC, eamanu requested changes

2023-11-06 00:37 UTC, eamanu commented on _sources/lectures/TWP20/toctree_en.rst
> +for, random and functions
no debría ser methods?

2023-11-06 00:37 UTC, eamanu commented on _sources/lectures/TWP52_en.rst
> ++ MVC - Model, Visión, Control
Debería ser Model-View-Control

2023-12-10 18:42 UTC, ivanuxowo commented on _sources/lectures/TWP20/toctree_en.rst
> +for, random and functions
Hola, revise el capitulo original (en español) y la guía habla de funciones: https://pyar.github.io/PyZombis/main/lectures/TWP20/TWP20_2.html

Gracias por la revisión, disculpas por la tardanza.

2023-12-10 18:49 UTC, ivanuxowo commented on _sources/lectures/TWP52_en.rst
> ++ MVC - Model, Visión, Control
Ya lo correjí, gracias por la revisión.

2023-12-10 23:06 UTC, NicolasSandoval commented
Hola @ivanuxowo! Gracias por el aporte. Abri un issue(#296) con el tema de nombres en la lectura MVC.

2023-12-16 11:13 UTC, merged