Adding Interactive Assignments "Lista de Exercícios I" as Quiz1
PyAr/PyZombis pull request #69
Opened 2021-03-30 19:47 UTC by angelasofiaremolinagutierrez

Partially solves #7 

I have added all exercises from "Lista de Exercícios I Python para Zumbis.pdf" with unit test from each excercise, in file Quiz1.rst

I fixed some small bugs that were happening because of an idented block on quiz5mcq.rst (see reference images below)

![Bug](https://user-images.githubusercontent.com/10239480/113046059-33b29c80-9165-11eb-87f0-173a02e8de3d.png)

![Bug2](https://user-images.githubusercontent.com/10239480/113046097-3e6d3180-9165-11eb-9a02-5e4fab7ec6c5.png)

2021-03-31 13:54 UTC, eamanu commented on _sources/quiz/Quiz5mcq.rst
> +
Estas dos líneas están a propósito

2021-03-31 20:21 UTC, angelasofiaremolinagutierrez commented on _sources/quiz/Quiz5mcq.rst
> +   ¿Qué imprime el siguiente programa (dado en forma de pseucódigo)? |br|
Sí, este espacio es el error de identación que menciono. En la imagen que adjunté en el PR, el error de "No correct answer specified" se daba porque hacia falta un espacio para que la pregunta estuviera dentro del bloque mchoice.

2021-03-31 20:22 UTC, angelasofiaremolinagutierrez commented on _sources/quiz/Quiz5mcq.rst
> +
Estas dos líneas que añadí fueron por error. Voy a hacer un commit para borrarlas y dejar un estándar de espacios entre problema y bloque de activecode.

2021-03-31 20:25 UTC, angelasofiaremolinagutierrez commented on _sources/quiz/Quiz5mcq.rst
> +
Esta línea es para cumplir el patrón de 4 líneas entre el enunciado del problema y el bloque de activecode.

2021-05-24 04:46 UTC, y-martinez requested changes
LGTM!! 🚀 

Un cambio sencillo :)

2021-05-24 04:46 UTC, y-martinez commented on _sources/quiz/Quiz1.rst
> +   Sabiendo que str() convierte valores numéricos en cadenas, calcule cuántos dígitos hay en 2 elevados a un millón. |br|
Puedes encerrar str() en doble ` para formatearlo en código así se ve más legible como función 😄

2021-05-24 14:54 UTC, LeoCumpli21 reviewed
Todo me parece que está bien. El único cambio adecuado es el que menciona @y-martinez.

2021-05-24 17:15 UTC, angelasofiaremolinagutierrez commented on _sources/quiz/Quiz1.rst
> +   Sabiendo que str() convierte valores numéricos en cadenas, calcule cuántos dígitos hay en 2 elevados a un millón. |br|
Listo ;) ya quedó corregido. Muchas gracias por la sugerencia, se ve mucho mejor.

2021-05-24 20:14 UTC, merged