Fixxed Quiz9
PyAr/PyZombis pull request #72
Opened 2021-04-03 00:50 UTC by LeoCumpli21

This PR:
- Fixes quiz 9 exercises.
- Enhances translation from Portuguese to Spanish.
- Enhances instructions of the exercises.

Most of Quiz 9 was looking like this:
![quiz9_ss](https://user-images.githubusercontent.com/80920858/113463615-1f300780-93e4-11eb-8820-664414725dff.PNG)

2021-05-22 18:25 UTC, reingart approved these changes
Looks good to me!

El nombre de algunas funciones están en inglés y otras en castellano, quizás deberíamos normalizar y definir un único idioma.

2021-05-24 14:31 UTC, y-martinez commented
> Looks good to me!
> 
> El nombre de algunas funciones están en inglés y otras en castellano, quizás deberíamos normalizar y definir un único idioma.

@angelasofiaremolinagutierrez y @LeoCumpli21 habíamos coincidido que el Inglés debería ser el lenguaje del nombre de las funciones y así normalizar en todos los quices 😄 igualmente podemos conversarlo en la reunión de hoy

2021-05-24 20:10 UTC, eamanu approved these changes

2021-05-24 20:24 UTC, reingart approved these changes

2021-05-24 20:24 UTC, reingart commented on _sources/quiz/Quiz9.rst
> +           self.assertEqual((mayor_extremo([2, 11, 3]), [3, 3, 3],"Esperado: [3,3,3]")
```suggestion
           self.assertEqual(mayor_extremo([2, 11, 3]), [3, 3, 3],"Esperado: [3,3,3]")
```

2021-05-24 20:36 UTC, eamanu requested changes

2021-05-24 20:36 UTC, eamanu commented on _sources/quiz/Quiz9.rst
> +           self.assertEqual(mayor_extremo([2, 2, 2]), [2, 2, 2],"Esperado: [2,2,2]"")
```suggestion
           self.assertEqual(mayor_extremo([2, 2, 2]), [2, 2, 2],"Esperado: [2,2,2]")
```

2021-05-24 20:37 UTC, reingart commented
Ver Bug nuevo: #76

2021-05-24 20:38 UTC, merged