Fixxed mayor_extremo exercise
PyAr/PyZombis pull request #77
Opened 2021-05-24 23:02 UTC by LeoCumpli21

Should work alright by now.

2021-05-24 23:33 UTC, eamanu approved these changes

2021-05-24 23:37 UTC, y-martinez requested changes

2021-05-24 23:37 UTC, y-martinez commented on _sources/quiz/Quiz9.rst
>     Ejemplos:|br|
Agrega el ` para formatear el True y el False así como la llamada en los ejemplos así como hiciste en los otros ejercicios 😄

2021-05-25 00:51 UTC, reingart approved these changes
Seems fixed: http://pyar.github.io/PyZombis/77/quiz/Quiz9.html
![Screenshot_2021-05-24 Quiz - 9 — Runestone Interactive Overview](https://user-images.githubusercontent.com/1041385/119423670-30a5d980-bcda-11eb-9cce-2b50a5f33c75.png)

2021-05-25 16:33 UTC, LeoCumpli21 commented on _sources/quiz/Quiz9.rst
>     Ejemplos:|br|
Ya quedó :)

2021-05-25 20:16 UTC, y-martinez approved these changes
LGTM!

2021-05-29 17:04 UTC, merged