Fix quizzes
PyAr/PyZombis pull request #81
Opened 2021-06-07 21:18 UTC by LeoCumpli21

## Summary

This PR closes LeoCumpli21/PyZombis#20. I added subtitles to the exercises as agreed with my fellow collaborators.

## Checklist

- [ ] Variables, function and comments are translated to Spanish
- [ ] Spell check done & typos fixed
- [ ] All python code is PEP8 compliant
- [ ] Test coverage with Playwright implemented
- [ ] Reviewers assigned (all peers & at least 1 mentor)

2021-06-08 00:36 UTC, NicolasSandoval commented
Good advance, but this is Quiz-1, right?

2021-06-08 02:17 UTC, angelasofiaremolinagutierrez reviewed
Everything looks ok to me. Just change the title of the PR to Quiz 1 instead of Quiz 9 as @NicolasSandoval noticed ;)

2021-06-08 02:44 UTC, LeoCumpli21 commented
> Good advance, but this is Quiz-1, right?

Indeed, I'll change it.

2021-06-08 02:45 UTC, LeoCumpli21 commented
> Everything looks ok to me. Just change the title of the PR to Quiz 1 instead of Quiz 9 as @NicolasSandoval noticed ;)

Done! :)

2021-06-08 03:48 UTC, y-martinez approved these changes
LGTM! 🚀

2021-06-08 04:07 UTC, y-martinez requested changes
I was checking all exercises and I figure out that the sixth has a problem, I didn't check them in my previous review 😅

![image](https://user-images.githubusercontent.com/6761059/121121340-64f6bb00-c7ed-11eb-9f32-edd515ff7d1c.png)

2021-06-08 15:10 UTC, y-martinez approved these changes

2021-06-08 18:58 UTC, angelasofiaremolinagutierrez approved these changes

2021-06-08 23:01 UTC, reingart approved these changes
Muy buen trabajo! y tambien los reviews!

Sugiero agregar los dos checks nuevos a https://github.com/PyAr/PyZombis/blob/master/.github/pull_request_template.md
- [x] lower_case_with_underscores notation for function/methods & variables names (not camelCase, except classes)
- [ ] Use python code for test locators, instead of exercise description or html/css

2021-06-09 02:01 UTC, eamanu reviewed
Comentarios menores

2021-06-09 02:01 UTC, eamanu commented on tests/test_quiz1.py
> +    page.click("text=def suma(n,m):")
```suggestion
    page.click("text=def suma(n, m):")

```

2021-06-09 02:01 UTC, eamanu commented on tests/test_quiz1.py
> +    page.press("text=def suma(n,m):", "ArrowDown")
```suggestion
    page.press("text=def suma(n, m):", "ArrowDown")

```

2021-06-09 02:01 UTC, eamanu commented on tests/test_quiz1.py
> +    page.press("text=def suma(n,m):", "Tab")
```suggestion
    page.press("text=def suma(n, m):", "Tab")

```

2021-06-09 02:01 UTC, eamanu commented on tests/test_quiz1.py
> +    page.type("text=def suma(n,m):", "return n+m")
```suggestion
    page.type("text=def suma(n, m):", "return n+m")

```

2021-06-09 02:02 UTC, eamanu approved these changes

2021-06-09 23:59 UTC, reingart approved these changes
LGTM

2021-06-09 23:59 UTC, reingart commented on tests/test_quiz3.py
> +              "return billetes")
- [x] Issue LeoCumpli21/PyZombis#27

2021-06-10 00:00 UTC, merged