Refactor quiz 6 file
PyAr/PyZombis pull request #86
Opened 2021-06-10 04:29 UTC by LeoCumpli21

## Summary

This PR closes LeoCumpli21/PyZombis#22 by:
1. Adding subtitles to each exercise as *Ejercicio #*
2. Changing each exercise's id to `q6_#`
3. Rewriting the instructions of each exercise so that they are comprehensible and the `rst` formatting doesn't mess up anything.
4. Making sure python code is PEP8 compliant. I used `flake8` for this.
5. Finally, I made a test with Playwright for ex 1 (see the attached video).

## Checklist

- [ ] Variables, functions and comments are translated to Spanish
- [ ] Functions follow underscore notation
- [ ] Spell check done & typos fixed
- [ ] All python code is PEP8 compliant
- [ ] Test coverage with Playwright implemented; locators are Pyhton code
- [ ] Reviewers assigned (all peers & at least 1 mentor)

## Screenshots

https://user-images.githubusercontent.com/80920858/121464567-b633b580-c979-11eb-9396-61de5dac92d5.mp4

2021-06-10 16:49 UTC, y-martinez requested changes
I left some comments and suggestions 👍🏼

2021-06-10 16:49 UTC, y-martinez commented on _sources/quiz/Quiz6.rst
> +   ``a_sonrie`` y ``b_sonrie`` indican si a y b sonríen. Cuando ambos ambos
```suggestion
   ``a_sonrie`` y ``b_sonrie`` indican si a y b sonríen. Cuando ambos 
```

2021-06-10 16:49 UTC, y-martinez commented on _sources/quiz/Quiz6.rst
> +   ``hablando`` que es ``True`` o ``False``, y ``hora`` que toma un valor
```suggestion
   ``hablando`` que puede ser ``True`` o ``False``, y ``hora`` que toma un valor 
```

2021-06-10 16:49 UTC, y-martinez commented on _sources/quiz/Quiz6.rst
> +   Desarrolle la función ``quitar_caracter`` que toma a ``s`` y ``n``
En el Quiz 7 hay un ejercicio igual [Ejercicio 13](http://pyar.github.io/PyZombis/master/quiz/Quiz7.html#ejercicio-13) creo que entonces debemos quitar ese y unir el enunciado de ese con este, si estas de acuerdo

2021-06-10 16:49 UTC, y-martinez commented on _sources/quiz/Quiz6.rst
> +   ``quitar_caracter('gatito', 1)`` -> ``'gtito'`` |br|
```suggestion
   ``quitar_caracter("gatito", 1)`` -> ``"gtito"`` |br|
```

2021-06-10 16:49 UTC, y-martinez commented on _sources/quiz/Quiz6.rst
> +   ``quitar_caracter('gatito', 4)`` -> ``'gatio'`` |br|
```suggestion
   ``quitar_caracter("gatito", 4)`` -> ``"gatio"`` |br|
```

2021-06-10 16:49 UTC, y-martinez commented on _sources/quiz/Quiz6.rst
> +   ``intercambiar('codigo')`` -> ``'oodigc'`` |br|
Cambiarlo como en la sugerencia de arriba 😃

2021-06-10 16:49 UTC, y-martinez commented on _sources/quiz/Quiz6.rst
> +   valores booleanos, es decir ``True`` o ``False``. La función actúa
```suggestion
   valores booleanos, es decir pueden ser ``True`` o ``False``. La función actúa 
```

2021-06-10 19:01 UTC, LeoCumpli21 commented on _sources/quiz/Quiz6.rst
> +   Desarrolle la función ``quitar_caracter`` que toma a ``s`` y ``n``
Me parece bien! enseguida copio el enunciado del quiz 7.

2021-06-10 19:19 UTC, LeoCumpli21 commented on _sources/quiz/Quiz6.rst
> +   ``intercambiar('codigo')`` -> ``'oodigc'`` |br|
Hecho :)

2021-06-10 20:45 UTC, y-martinez approved these changes
LGTM 🚀

2021-06-12 02:55 UTC, reingart approved these changes
Me perdí bastante en el diff para analizar los cambios, porque se mezclan mucho los ejercicios
Voy a esperar por si hay otro mentor que pueda revisarlo mejor

2021-06-13 02:48 UTC, NicolasSandoval approved these changes
LGTM!

2021-06-14 01:12 UTC, merged