Updated quiz9 to follow conventions
PyAr/PyZombis pull request #88
Opened 2021-06-10 22:52 UTC by LeoCumpli21

## Summary

This PR closes LeoCumpli21/PyZombis#23 by:
1. Adding subtitles to each exercise (*Ejercicio #*)
2. Translating variable and function names to Spanish and writing them in underscore notation.
3. Checking python code is PEP8 compliant with `flake8`.
4. Adding a playwright test for ex 1 (watch the attached video).

## Checklist

- [ ] Variables, functions and comments are translated to Spanish
- [ ] Functions follow underscore notation
- [ ] Spell check done & typos fixed
- [ ] All python code is PEP8 compliant
- [ ] Test coverage with Playwright implemented; locators are Pyhton code
- [ ] Reviewers assigned (all peers & at least 1 mentor)

## Screenshots

(prefer Playwright recorded video or animated gif)

https://user-images.githubusercontent.com/80920858/121606853-87b6e880-ca14-11eb-8a91-643d24c6d09b.mp4

2021-06-10 23:00 UTC, LeoCumpli21 commented on _sources/quiz/Quiz9.rst
> +   Define una función ``cita_de_lujo``. La función tomará dos dos parámetros
```suggestion
   Define una función ``cita_de_lujo``. La función tomará dos parámetros 
```

2021-06-11 15:40 UTC, y-martinez requested changes
A few comments but in general it is good 👍🏼

2021-06-11 15:40 UTC, y-martinez commented on _sources/quiz/Quiz9.rst
> +           self.assertEqual(poner_alarma(1, False), '7:00', "Esperado: 7:00")
Trata de cambiar los ``' '`` por ``" "`` si quieres corre la herramienta ``black`` con las porciones de codigo de python para que arregle esas cositas.

2021-06-11 15:40 UTC, y-martinez commented on _sources/quiz/Quiz9.rst
> +   determinará si les dan una mesa en el restaurante o no:|br|
```suggestion
   determinará si les dan una mesa en el restaurante o no, de acuerdo a las siguientes reglas:|br|
```

2021-06-11 15:40 UTC, y-martinez commented on _sources/quiz/Quiz9.rst
> +   Entonces ``cita_de_lujo`` devuelve un número entre 0, 1 y 2: 0 = no, 1 = tal vez y 2 = sí |br| |br|
```suggestion
   Entonces ``cita_de_lujo`` devuelve un número entre 0, 1 y 2 que significan No, Tal vez y Si respectivamente |br| |br|
```

2021-06-11 15:40 UTC, y-martinez commented on _sources/quiz/Quiz9.rst
> +   la temperatura, y ``es_verano``, que puede ser ``True`` si es verano o ``False``.
```suggestion
   la temperatura, y ``es_verano``, que puede ser ``True`` si es verano o ``False`` si no lo es. 
```

2021-06-11 15:40 UTC, y-martinez commented on _sources/quiz/Quiz9.rst
> +   ``poner_alarma(1, False)`` -> ``'7:00'`` |br|
Igual aqui las dobles comillas

2021-06-11 15:58 UTC, LeoCumpli21 commented on _sources/quiz/Quiz9.rst
> +   ``poner_alarma(0, False)`` -> ``'10:00'`` |br|
```suggestion
   ``poner_alarma(1, False)`` -> ``"7:00"`` |br|
   ``poner_alarma(1, True)`` -> ``"10:00"`` |br|
   ``poner_alarma(6, True)`` -> ``"libre"`` |br|
   ``poner_alarma(0, False)`` -> ``"10:00"`` |br|
```

2021-06-11 16:04 UTC, LeoCumpli21 commented on _sources/quiz/Quiz9.rst
> +           self.assertEqual(poner_alarma(1, False), '7:00', "Esperado: 7:00")
Listo! muy buena herramienta btw 👍🏽

2021-06-11 16:55 UTC, y-martinez approved these changes
LGTM 🚀

2021-06-12 02:25 UTC, reingart approved these changes
LGTM

2021-06-12 02:43 UTC, merged