Improve the quiz10 and test
PyAr/PyZombis pull request #92
Opened 2021-06-13 02:33 UTC by y-martinez

## Summary

Close y-martinez/PyZombis#15

## Checklist

- [X] Variables, functions and comments are translated to Spanish
- [X] Functions follow underscore notation
- [X] Spell check done & typos fixed
- [X] All python code is PEP8 compliant
- [X] Test coverage with Playwright implemented; locators are Pyhton code
- [X] Reviewers assigned (all peers & at least 1 mentor)

## Screenshots

(prefer Playwright recorded video or animated gif)

2021-06-13 20:03 UTC, LeoCumpli21 commented on _sources/quiz/Quiz10.rst
> +    Desarrolle la función llamada ``suma_con_suerte`` que recibe tres números enteros ``a``, ``b`` y ``c``. La función debe devolver la suma de los tres números con la condición de que si uno de los
```suggestion
    Desarrolle la función llamada ``suma_con_suerte`` que recibe tres números enteros ``a``, ``b`` y ``c``. La función debe devolver la suma de los tres números con la condición de que si uno de los números es el **13**, éste no cuenta en la suma así como todos los números que se encuentren a su derecha. |br| |br|
```

2021-06-13 20:05 UTC, LeoCumpli21 commented on _sources/quiz/Quiz10.rst
> +    Desarrolle la función, ``contar_saludo`` que recibe como parámetro una cadena ``s`` y devuelve el número de veces que aparece la cadena ``"hola"`` en ``s`` |br| |br|
```suggestion
    Desarrolle la función, ``contar_saludo`` que recibe como parámetro una cadena ``s`` y devuelve el número de veces que aparece la cadena ``"hola"`` en ``s``. |br| |br|
```

2021-06-13 20:09 UTC, LeoCumpli21 commented on _sources/quiz/Quiz10.rst
> +    Desarrolle la función ``gato_perro`` que recibe como parámetro una cadena ``s`` y devuelve ``True`` si en la cadena ``s`` aparece el mismo número de veces la cadena "gato" y la cadena "perro" o d
Aquí me parece bueno poner las cadenas con el formato de código, justo como en el ejercicio de arriba donde dice
> la cadena `"hola"`

```suggestion
    Desarrolle la función ``gato_perro`` que recibe como parámetro una cadena ``s`` y devuelve ``True`` si en la cadena ``s`` aparece el mismo número de veces la cadena ``"gato"`` y la cadena ``"perro"`` o devuelve ``False`` en caso contrario. |br| |br|
```

2021-06-13 20:10 UTC, LeoCumpli21 commented on _sources/quiz/Quiz10.rst
> +    Desarrolle la función ``contar_code`` que recibe como parámetro una cadena ``s`` y devuelve el número de veces que aparece la cadena ``"code"`` en ``s`` pero con la condición de que la letra ``'s
```suggestion
    Desarrolle la función ``contar_code`` que recibe como parámetro una cadena ``s`` y devuelve el número de veces que aparece la cadena ``"code"`` en ``s`` pero con la condición de que la letra ``'s'`` puede ser intercambiada por cualquier otra. Así, las cadenas ``"coze"`` y ``"coxe"`` deben ser contadas igualmente. |br| |br|
```

2021-06-13 20:14 UTC, LeoCumpli21 commented on _sources/quiz/Quiz10.rst
> +    Sabiendo que la función ``lower()`` convierte los carácteres de una cadena en minúsculas. Desarrolle una función llamada ``finales_iguales`` que recibe dos cadenas ``a`` y ``b``` como parámetros.
```suggestion
    Sabiendo que la función ``lower()`` convierte los carácteres de una cadena en minúsculas. Desarrolle una función llamada ``finales_iguales`` que recibe dos cadenas ``a`` y ``b``` como parámetros. La función devolverá ``True`` si al final de la cadena ``a`` se encuentra la cadena ``b`` o si al final de la cadena ``b`` se encuentra la cadena ``a``. |br| |br|
```

2021-06-13 20:16 UTC, LeoCumpli21 commented on _sources/quiz/Quiz10.rst
> +    Desarrolle la función ``suma_con_mas_suerte`` que recibe una lista ``numeros`` de números enteros y devolver la suma de los números de lista con la condición de que si uno de los números es el **
```suggestion
    Desarrolle la función ``suma_con_mas_suerte`` que recibe una lista ``numeros`` de números enteros y devuelve la suma de los números de la lista con la condición de que si uno de los números es el **13**, éste no cuenta en la suma asi como todos los números que se encuentren a su derecha. |br| |br|
```

2021-06-13 20:18 UTC, LeoCumpli21 commented on _sources/quiz/Quiz10.rst
> +    Desarrolle la función ``tiene_2`` que recibe como parámetro una lista ``numeros`` de números enteros y devolver ``True`` si en la lista aparecen dos números consecutivos y ``False`` en caso contr
```suggestion
    Desarrolle la función ``tiene_2`` que recibe como parámetro una lista ``numeros`` de números enteros y devuelve ``True`` si en la lista aparecen dos números iguales consecutivos y ``False`` en caso contrario. |br| |br|
```

2021-06-13 20:27 UTC, LeoCumpli21 approved these changes
LGTM! :smiley:

2021-06-14 04:03 UTC, angelasofiaremolinagutierrez requested changes
This is ready to merge! Just add the minor changes I suggested ;)

2021-06-14 04:03 UTC, angelasofiaremolinagutierrez commented on _sources/quiz/Quiz10.rst
> +    Sabiendo que la función ``lower()`` convierte los carácteres de una cadena en minúsculas. Desarrolle una función llamada ``finales_iguales`` que recibe dos cadenas ``a`` y ``b``` como parámetros.
```suggestion
    Sabiendo que la función ``lower()`` convierte los carácteres de una cadena en minúsculas. Desarrolle una función llamada ``finales_iguales`` que recibe dos cadenas ``a`` y ``b`` como parámetros. La función devolverá ``True`` si al final de la cadena ``a`` se encuentra la cadena ``b`` o si al final de la cadena ``b`` se encuentra la cadena ``a``. |br| |br|
```

2021-06-14 16:06 UTC, y-martinez commented on _sources/quiz/Quiz10.rst
> +    Desarrolle la función ``contar_code`` que recibe como parámetro una cadena ``s`` y devuelve el número de veces que aparece la cadena ``"code"`` en ``s`` pero con la condición de que la letra ``'s
You are right! 👍🏼

2021-06-14 16:06 UTC, y-martinez commented on _sources/quiz/Quiz10.rst
> +    Desarrolle la función ``cerca_de_10`` que recibe un entero ``n`` y devuelve ``True`` cuando ``n`` sea múltiplo de 10, o esté a dos unidades de serlo, o ``False`` en caso contrario. |br| |br|
Yes, that is a better explanation.

2021-06-15 03:56 UTC, angelasofiaremolinagutierrez approved these changes

2021-06-16 02:50 UTC, NicolasSandoval approved these changes

2021-06-16 02:50 UTC, NicolasSandoval commented on _sources/quiz/Quiz10.rst
> +            self.assertEqual(construir_fila(3, 2, 9), False, "Esperado: False")
Check tests.

2021-06-16 02:51 UTC, merged