Fix quiz 13 and add Playwright test
PyAr/PyZombis pull request #95
Opened 2021-06-14 19:12 UTC by LeoCumpli21

## Summary

This PR closes LeoCumpli21/PyZombis#25 by:
1. Adding subtitles and correct ID's to each exercise.
2. Translating the whole file to Spanish.
3. Adding a `playwright` test and formatting with `black`.

## Checklist

- [ ] Variables, functions and comments are translated to Spanish
- [ ] Functions follow underscore notation
- [ ] Spell check done & typos fixed
- [ ] All python code is PEP8 compliant
- [ ] Test coverage with Playwright implemented; locators are Pyhton code
- [ ] Reviewers assigned (all peers & at least 1 mentor)

## Screenshots

https://user-images.githubusercontent.com/80920858/121946347-745c9380-cd1a-11eb-95c2-f41df52a5072.mp4

2021-06-14 23:40 UTC, y-martinez requested changes
I left some little suggestions 👍🏼

2021-06-14 23:40 UTC, y-martinez commented on _sources/quiz/Quiz13.rst
> +   Desarrolle la función ``terminan_igual`` que, dada una lista de cadenas, devuelva el número de cadenas
```suggestion
   Desarrolle la función ``terminan_igual`` que, dada una lista de cadenas ``palabras``, devuelva el número de cadenas
```

2021-06-14 23:40 UTC, y-martinez commented on _sources/quiz/Quiz13.rst
> +   otra lista en la que todos los elementos que comienzan con ``"x"`` sean los primeros en la lista.
```suggestion
   otra lista en la que todas las cadenas que comienzan con el carácter ``'x'`` sean los primeros elementos de la lista. 
```

2021-06-19 22:24 UTC, NicolasSandoval approved these changes
Great work!

2021-06-19 22:25 UTC, merged